export enum KycStatus {
  DRAFT = 'DRAFT',
  PENDING_DOCS = 'PENDING_DOCS',
  PROCESSING = 'PROCESSING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ACTION_REQUIRED = 'ACTION_REQUIRED',
  REVIEW_NEEDED = 'REVIEW_NEEDED',
}

export enum DocumentType {
  PASSPORT = 'PASSPORT',
  NATIONAL_ID = 'NATIONAL_ID',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  TAX_ID = 'TAX_ID',
  UTILITY_BILL = 'UTILITY_BILL',
  CERTIFICATE_OF_INCORPORATION = 'CERTIFICATE_OF_INCORPORATION',
}
